src/ArduinoOcpp.cpp, src/ArduinoOcpp.h, src/ArduinoOcpp/Tasks/Metering/SampledValue.h
Solves #112 , @matth-x  sorry about the delay
As mentioned in the issue, many Central Systems require precise measurements of MeterValues. In applications like this using float values is fundamental.
=> AddMeterValueInput accepts float values

examples/SECC/README.md, examples/SECC/main.cpp
ESP32 `ledcWrite` expects the pwm channel and dutycycle, see: [ledcWrite](https://github.com/espressif/arduino-esp32/blob/0d84018d969309addacbcc3e3782c1fadc95fbc8/cores/esp32/esp32-hal-ledc.c#L82).
At the moment this function is called with the GPIO pin number resulting in an infunctional pwm output.
The PR fixes this issue and adds an ESP32 specific parameter `PWM_CHANNEL`.
=> Fix ESP32 PWM configuration fault in SECC example

src/ArduinoOcpp/Core/ConfigurationKeyValue.cpp, src/ArduinoOcpp/Core/Connection.cpp, src/ArduinoOcpp/Core/Connection.h, src/ArduinoOcpp/Core/RequestQueue.cpp, src/ArduinoOcpp/Core/RequestQueue.h
This PR changes the retry strategy of the Request queue. Instead of detecting offline periods and retrying after becoming online again, the new behavior only checks for WebSocket reconnects. The additional default backoff period of 15s has been extended to 4 minutes.
The previous strategy lead to a high number of duplicate messages with matching `messageId`s. The OCPP standard doesn't define how to handle multiple messages with the same ID and tests with different OCPP backends show that this behavior is problematic.
To support checking for reconnects, the `Connection` interface has a new function `ulong getLastConnected()` which returns the timestamp when the last underlying WebSocket connection was successfully established.
=> Retry msg send only after WebSocket reconnect

.github/workflows/tests.yml, tests/ChargingSessions.cpp
Add workflow steps for the unit tests:
- execute tests with valgrind
- compile and execute with AddressSanitizer, UndefinedBehaviorSanitizer
Furthermore this PR contains a bugfix in a unit test that is related to address sanitation
=> add valgrind, ASan, UBSan

CMakeLists.txt, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/Reservation/Reservation.cpp, src/MicroOcpp/Model/Reservation/Reservation.h, src/MicroOcpp/Model/Reservation/ReservationService.cpp, src/MicroOcpp/Model/Reservation/ReservationService.h, src/MicroOcpp/Operations/ReserveNow.cpp, tests/Configuration.cpp, tests/Reservation.cpp
Unit tests for the Reservation feature profile, corresponding fixes and minor cosmetic changes to simplify the handling of the ReservationService in the test cases.
Fixes #191 and #154.
=> Unit tests for Reservation

src/MicroOcpp/Model/Diagnostics/DiagnosticsService.cpp, src/MicroOcpp/Model/Diagnostics/DiagnosticsService.h, src/MicroOcpp/Model/FirmwareManagement/FirmwareService.cpp, src/MicroOcpp/Model/FirmwareManagement/FirmwareService.h, src/MicroOcpp/Operations/GetDiagnostics.cpp, src/MicroOcpp/Operations/GetDiagnostics.h, src/MicroOcpp/Operations/RemoteStartTransaction.cpp, src/MicroOcpp/Operations/RemoteStartTransaction.h, src/MicroOcpp/Operations/RemoteStopTransaction.cpp, src/MicroOcpp/Operations/RemoteStopTransaction.h, src/MicroOcpp/Operations/TriggerMessage.cpp, src/MicroOcpp/Operations/TriggerMessage.h, src/MicroOcpp/Operations/UpdateFirmware.cpp, src/MicroOcpp/Operations/UpdateFirmware.h
For some incoming operation types, the operation was executed inside the `createConf()` handler. This could glitch when sending the confirmation is attempted multiple times, e.g. when the device is getting offline. 
While fixing this, some function signatures of the DiagnosticsService and FirmwareService were updated to match the current coding style, i.e. `const std::string&` became `const char*` and `int` became `unsigned int` where appropriate.
=> Fix multiple operation executions and update FW-/DiagService API

CMakeLists.txt, src/MicroOcpp/Core/RequestQueue.cpp, src/MicroOcpp/Model/Authorization/AuthorizationList.cpp, src/MicroOcpp/Model/Authorization/AuthorizationList.h, src/MicroOcpp/Model/Authorization/AuthorizationService.cpp, src/MicroOcpp/Model/Authorization/AuthorizationService.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.h, src/MicroOcpp/Model/ConnectorBase/ConnectorsCommon.cpp, src/MicroOcpp/Operations/ChangeAvailability.cpp, src/MicroOcpp/Operations/CustomOperation.cpp, src/MicroOcpp/Operations/CustomOperation.h, src/MicroOcpp/Operations/SendLocalList.cpp, src/MicroOcpp/Operations/SendLocalList.h, tests/LocalAuthList.cpp
Adding unit tests for the Authorization module. The Authorization module was restructured a bit for better testability. While creating the unit tests, the following defects were found and fixed:
- The configuration ConnectionTimeOut limited the duration of the overall Preparation phase. Now it's restricted to only abort the transaction process if the EVSE is not plugged early enough.
- LocalPreAuthorize was disabled too when LocalAuthorizeOffline was false
- SendLocalList with updateType Full also expected an incrementing listVersion. This only applies to Differential updates now
=> Unit tests for LocalAuthLists

src/MicroOcpp/Model/FirmwareManagement/FirmwareService.cpp
When entering UpdateStage::Downloading the update was aborted immediately because neither DownloadStatus::Downloaded nor DownloadStatus::DownloadFailed was present and so the firmwareService loop executes firmware update failed. This resets the state machine and the update never reaches the install stage.
=> fixed state transition issue in FirmwareService

src/MicroOcpp/Core/FilesystemAdapter.cpp, src/MicroOcpp/Core/FilesystemAdapter.h
Hi @matth-x,
If you use more than one spiffs partition in your project, it makes sense to adjust the .base_path of the partitions so that it is not just "/".
In the current version, however, this unfortunately leads to problems when using the esp-idf:
if you set the base_path to "/mo/", for example, you get an invalid argument error when initialising the spiffs partition, as the base path must not contain a slash at the end.
if you set the base_path to "/mo", the initialisation works, but the file names are no longer correct because they do not begin with a "/". An attempt is then made to save /mobootstats.jsn, for example, which does not work.
For this reason, a check has been introduced which, when setting the base_path, checks whether a "/" is present at the end of the define …
=> adapted esp-idf spiffs initialization

examples/ESP/main.cpp, src/MicroOcpp.cpp, src/MicroOcpp.h
This PR changes the signature of `mocpp_initialize(const char *host, ...)`. Instead of an OCPP host, port and URL, it expects the OCPP backend URL and the chargeBoxId. This aligns better with the typical instructions of OCPP backends.
For example, the previous notation
```cpp
const char *host = "my.instance.com";
uint16_t port = 8443;
const char *url = "wss://my.instance.com/steve/websocket/CentralSystemService/charger001";
mocpp_initialize(host, port, url);
```
becomes
```cpp
const char *backendUrl = "wss://my.instance.com:8443/steve/websocket/CentralSystemService";
const char *chargeBoxId = "charger001";
mocpp_initialize(backendUrl, chargeBoxId);
```
=> parse URL instead of explicit host param

CHANGELOG.md, src/MicroOcpp/Model/SmartCharging/SmartChargingModel.cpp, src/MicroOcpp/Model/SmartCharging/SmartChargingService.cpp, src/MicroOcpp/Operations/SetChargingProfile.cpp
During tests, three defects were found:
- Config `ChargingScheduleMaxPeriods` was ignored when interpreting charging schedules
- The installed profiles were not counted correctly, allowing to install more profiles than defined by `MaxChargingProfilesInstalled`
- The transactionId of the TxProfile wasn't checked against the currently running transaction
Thanks again to the engineer who reported all these defects.
=> Smart Charging module fixes

CHANGELOG.md, CMakeLists.txt, README.md, src/MicroOcpp.cpp, src/MicroOcpp.h, src/MicroOcpp/Model/Certificates/Certificate.cpp, src/MicroOcpp/Model/Certificates/Certificate.h, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.cpp, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.h, src/MicroOcpp/Model/Certificates/CertificateService.cpp, src/MicroOcpp/Model/Certificates/CertificateService.h, src/MicroOcpp/Model/Certificates/Certificate_c.cpp, src/MicroOcpp/Model/Certificates/Certificate_c.h, src/MicroOcpp/Model/Model.cpp, src/MicroOcpp/Model/Model.h, src/MicroOcpp/Operations/DeleteCertificate.cpp, src/MicroOcpp/Operations/DeleteCertificate.h, src/MicroOcpp/Operations/GetInstalledCertificateIds.cpp, src/MicroOcpp/Operations/GetInstalledCertificateIds.h, src/MicroOcpp/Operations/InstallCertificate.cpp, src/MicroOcpp/Operations/InstallCertificate.h, src/MicroOcpp/Version.h, src/MicroOcpp_c.cpp, src/MicroOcpp_c.h, tests/Certificates.cpp, tests/LocalAuthList.cpp
Add support for CSMS certificates based on the OCPP 1.6 Security white paper / OCPP 2.0.1 use cases M03 - M05.
Implemented OCPP messages:
- DeleteCertificate
- GetInstalledCertificateIds
- InstallCertificate
The certificate management can be used in two fashions:
- The OCPP lib receives the requests from the server and forwards them to the certificate manager of the host system
- The OCPP lib recieves the requests and implements a minimal certificate manager to process them. The certs are stored on the flash file system and the host TLS client can access them by reading the cert files.
To integrate the certificate manager of the host system, an adapter of the `CertificateStore` interface needs to be passed to mocpp_initialize(...) during the initialization. If the integration is in …
=> Certificate Management (UCs M03 - M05)

src/MicroOcpp/Model/Authorization/IdToken.cpp, src/MicroOcpp/Model/Authorization/IdToken.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/ConnectorBase/ConnectorsCommon.cpp, src/MicroOcpp/Model/Transactions/Transaction.h, src/MicroOcpp/Model/Transactions/TransactionService.cpp, src/MicroOcpp/Model/Transactions/TransactionService.h, src/MicroOcpp/Operations/Authorize.cpp, src/MicroOcpp/Operations/Authorize.h, src/MicroOcpp/Operations/TransactionEvent.cpp, src/MicroOcpp/Operations/TransactionEvent.h, tests/Transactions.cpp
The transactions state machine got stuck for some event sequences. This PR contains a redesign of the Tx implementation which returns to a consistent state more reliably.
=> Fix OCPP 2.0.1 transactions

CMakeLists.txt, src/MicroOcpp/Core/FilesystemAdapter.cpp, src/MicroOcpp/Core/FilesystemAdapter.h, src/MicroOcpp/Core/FilesystemUtils.cpp
Add an index of all stored files in the OCPP folder on the filesystem. MO will look up if a file exists using the index instead of the host system's `stat` implementation.
On SPIFFS, a high memory usage can lead to a significant slowdown of file operations. That is especially a problem for `stat` which MicroOcpp uses often and in bursts. The index is a minimal data structure which keeps track of all files existing in the OCPP folder and thereby avoiding `stat` after the initial enrollment.
To enable, set the build flag `MO_ENABLE_FILE_INDEX=1` (disabled by default).
Use it with caution. If MO uses this file index implementation, then all operations on the MO files must go through the same file index instance. This is relevant if files are changed manually while MO is running.
=> Add filesystem index structure

src/MicroOcpp/Model/Certificates/Certificate.cpp, src/MicroOcpp/Model/Certificates/Certificate.h, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.cpp, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.h, src/MicroOcpp/Model/Certificates/Certificate_c.cpp, src/MicroOcpp/Model/Certificates/Certificate_c.h, src/MicroOcpp/Operations/DeleteCertificate.cpp, src/MicroOcpp/Operations/GetInstalledCertificateIds.cpp, src/MicroOcpp/Operations/InstallCertificate.cpp, src/MicroOcpp_c.cpp, src/MicroOcpp_c.h, tests/Certificates.cpp
Tests of the certificate management revealed some issues. This PR contains the corresponding fixes. Furthermore, the data structures are more interoperable with C now. This is to evaluate if using less C++ features simplifies creating the C-API.
=> OCPP 2.0.1 Certificate management fixes / Certs C-API rework

src/MicroOcpp/Core/RequestQueueStorageStrategy.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/Metering/MeteringConnector.cpp, src/MicroOcpp/Operations/StopTransaction.cpp
The transaction queue could get stuck if PreBootTransactions were enabled (i.e. the charger is allowed to start transactions before the BootNotification succeeds). This PR contains the corresponding fixes.
Furthermore, the format specifier `PRId32` caused problems with `int` and this PR changes it to `%d`.
=> Fix transactions freeze in offline mode

src/MicroOcpp/Model/Transactions/Transaction.h, src/MicroOcpp/Model/Transactions/TransactionService.cpp, src/MicroOcpp/Model/Transactions/TransactionService.h, src/MicroOcpp/Operations/TransactionEvent.cpp, src/MicroOcpp/Operations/TransactionEvent.h
Apply the same concepts of the OCPP 1.6 tx implementation to 2.0.1 txs. This will facilitate 1.6-2.0.1 interoperability.
=> Revise OCPP 2.0.1 transactions

CHANGELOG.md, src/MicroOcpp/Core/Connection.cpp, src/MicroOcpp/Core/Connection.h, src/MicroOcpp/Core/Context.cpp, src/MicroOcpp/Core/Context.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, tests/ChargingSessions.cpp, tests/ConfigurationBehavior.cpp, tests/LocalAuthList.cpp
Check the connectivity status of the WebSocket before sending an Authorize request to find out if the charger is offline. 
Previously, MO always tried to send the Authorize request and entered the offline mode when Authorize timed out (after 20 seconds by default).
To implement this, the Connection allows checking if it's offline via `isConnected()`. Furthermore, the transaction logic needs access to the Connection instance.
=> Fall back to offline authorization immediately when WebSocket unconnected

CHANGELOG.md, src/MicroOcpp.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/Transactions/TransactionService.cpp, src/MicroOcpp/Model/Transactions/TransactionService.h, src/MicroOcpp/Operations/ChangeAvailability.cpp
Update `ocppPermitsCharge()` in MicroOcpp.h so that it determines the charge permission based on the selected OCPP version.
Furthermore, upgrade ChangeAvailability to be OCPP 2.0.1 compatible.
=> OCPP 2.0.1 Add ocppPermitsCharge()

CHANGELOG.md, SConscript.py, src/MicroOcpp/Core/RequestQueueStorageStrategy.cpp, src/MicroOcpp/Model/Diagnostics/DiagnosticsService.cpp, src/MicroOcpp/Model/Transactions/Transaction.cpp, src/MicroOcpp/Model/Transactions/Transaction.h, src/MicroOcpp/Model/Transactions/TransactionDeserialize.cpp, src/MicroOcpp/Operations/GetConfiguration.cpp, tests/ChargingSessions.cpp
This PR adds patches thankfully released from a MicroOcpp integration.
- invalid access during restoring offline txs which could crash the microcontroller
- minor fixes
- more test cases for offline transactions
- basic SCons integration
=> Fixes from integration, basic SCons integration

CHANGELOG.md, src/MicroOcpp/Core/Request.cpp
Change the order of when the Operation methods get called. Applies to incoming requests.
Before (on error): create confirmation response, then check if Operation instance returns error code, then discard confirmation and respond with error code.
Now (on error): check if Operation instance returns error code, respond with error code.
=> Eval operation error code before creating conf

CMakeLists.txt, src/MicroOcpp.cpp, src/MicroOcpp/Core/Ftp.h, src/MicroOcpp/Core/FtpMbedTLS.cpp, src/MicroOcpp/Core/FtpMbedTLS.h, src/MicroOcpp/Debug.h, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.cpp, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.h, src/MicroOcpp/Platform.h
Migrate [MicroFtp](https://github.com/matth-x/MicroFtp) into this repository.
The OCPP 1.6 Security white paper and OCPP 2.0.1 add more use cases which require an FTP connection. A built-in FTP client makes the integration of MicroOcpp easier. It will be possible to disable the built-in implementation and use a custom client instead (e.g. if the host system already provides FTP).
=> Move FTP client into MicroOcpp

.github/workflows/tests.yml, .gitignore, CHANGELOG.md, CMakeLists.txt, src/MicroOcpp.cpp, src/MicroOcpp.h, src/MicroOcpp/Core/FtpMbedTLS.cpp, src/MicroOcpp/Model/Certificates/Certificate.cpp, src/MicroOcpp/Model/Certificates/Certificate.h, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.cpp, src/MicroOcpp/Model/Certificates/CertificateMbedTLS.h, src/MicroOcpp/Model/Certificates/CertificateService.cpp, src/MicroOcpp/Model/Certificates/CertificateService.h, src/MicroOcpp/Model/Certificates/Certificate_c.cpp, src/MicroOcpp/Model/Certificates/Certificate_c.h, src/MicroOcpp/Model/Model.cpp, src/MicroOcpp/Model/Model.h, src/MicroOcpp/Operations/DeleteCertificate.cpp, src/MicroOcpp/Operations/DeleteCertificate.h, src/MicroOcpp/Operations/GetInstalledCertificateIds.cpp, src/MicroOcpp/Operations/GetInstalledCertificateIds.h, src/MicroOcpp/Operations/InstallCertificate.cpp, src/MicroOcpp/Operations/InstallCertificate.h, src/MicroOcpp/Version.h, src/MicroOcpp_c.cpp, src/MicroOcpp_c.h, tests/Certificates.cpp
Add a global integration of MbedTLS into MicroOcpp.
At the moment, there are two (optional) features of MicroOcpp which relate to TLS:
- Certificate Management (UCs M03 - M05)
- FTP client
The Certificate Management module consists of an ordinary messaging part which does not depend on MbedTLS (can be reused with other TLS libraries) and a reference implementation of the required X.509 certificate parsing and storage functions which do depend on MbedTLS.
With this PR, the following switches exist to control the TLS-related modules:
- `MO_ENABLE_MBEDTLS=1`: enable modules which depend on MbedTLS
- `MO_ENABLE_CERT_MGMT=1`: enable general Certificate Management support
- `MO_ENABLE_CERT_STORE_MBEDTLS=1`: enable Certificate Management X.509 parsing and storage implementation
cmake switches:
- …
=> Add more build switches for TLS

CHANGELOG.md, CMakeLists.txt, src/MicroOcpp/Core/ConfigurationKeyValue.cpp, src/MicroOcpp/Core/ConfigurationKeyValue.h, src/MicroOcpp/Core/Configuration_c.cpp, src/MicroOcpp/Core/Configuration_c.h, tests/Configuration.cpp
Port the API for custom Config store implementations from C++ to C.
=> C-API for custom Configurations store

CHANGELOG.md, src/MicroOcpp.cpp, src/MicroOcpp.h, src/MicroOcpp/Model/Metering/SampledValue.cpp, src/MicroOcpp/Model/Metering/SampledValue.h, src/MicroOcpp/Platform.cpp, src/MicroOcpp/Platform.h, tests/Metering.cpp
Change the data type of the default EnergyMeterInput to int.
It may be necessary to patch the data format in the host system integration. For example, the previous usage
```cpp
setEnergyMeterInput([] () -> float {
return /* energy_register */;
});
```
would become
```cpp
setEnergyMeterInput([] () -> int {
return /* (int) energy_register */;
});
```
Furthermore, this PR fixes the float format in MeterValues which contained white spaces in some scenarios (e.g. `" 0.0"`).
=> Update / fix MeterValues format

CHANGELOG.md, src/MicroOcpp.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/Model.cpp, src/MicroOcpp/Model/Model.h, src/MicroOcpp/Model/Reservation/Reservation.cpp, src/MicroOcpp/Model/Reservation/Reservation.h, src/MicroOcpp/Model/Reservation/ReservationService.cpp, src/MicroOcpp/Model/Reservation/ReservationService.h, src/MicroOcpp/Operations/CancelReservation.cpp, src/MicroOcpp/Operations/CancelReservation.h, src/MicroOcpp/Operations/ReserveNow.cpp, src/MicroOcpp/Operations/ReserveNow.h, src/MicroOcpp/Version.h, tests/Reservation.cpp
Add build flag `MO_ENABLE_V16_RESERVATION` which allows to disable the Reservation functionality.
As a result of disabling the Reservation module, MicroOcpp rejects incoming ReserveNow and CancelReservation messages and does not advertise Reservation support in the SupportedFeatureProfiles configuration. All code is excluded from the compiled firmware, which saves some flash space on top.
To disable Reservation, set the build flag `MO_ENABLE_V16_RESERVATION=0`. The Reservation module is enabled by default, so `MO_ENABLE_V16_RESERVATION` doesn't need to be explicitly set to 1 otherwise.
=> Allow to disable Reservation module

CHANGELOG.md, src/MicroOcpp.cpp, src/MicroOcpp/Model/Authorization/AuthorizationData.cpp, src/MicroOcpp/Model/Authorization/AuthorizationData.h, src/MicroOcpp/Model/Authorization/AuthorizationList.cpp, src/MicroOcpp/Model/Authorization/AuthorizationList.h, src/MicroOcpp/Model/Authorization/AuthorizationService.cpp, src/MicroOcpp/Model/Authorization/AuthorizationService.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/Model.cpp, src/MicroOcpp/Model/Model.h, src/MicroOcpp/Operations/Authorize.cpp, src/MicroOcpp/Operations/GetLocalListVersion.cpp, src/MicroOcpp/Operations/GetLocalListVersion.h, src/MicroOcpp/Operations/SendLocalList.cpp, src/MicroOcpp/Operations/SendLocalList.h, src/MicroOcpp/Operations/StartTransaction.cpp, src/MicroOcpp/Operations/StopTransaction.cpp, src/MicroOcpp/Version.h, tests/ConfigurationBehavior.cpp, tests/LocalAuthList.cpp
Add build flag `MO_ENABLE_LOCAL_AUTH` which allows to disable the LocalAuthListManagement functionality.
The changes in this PR are same like the PR before (#302) for the Local Auth List functionality instead of Reservation. See the extended description there.
=> Allow to disable Local Authorization module

CHANGELOG.md, CMakeLists.txt, library.json, library.properties, src/MicroOcpp.cpp, src/MicroOcpp.h, src/MicroOcpp/Model/Authorization/AuthorizationService.cpp, src/MicroOcpp/Model/ConnectorBase/ChargePointStatus.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.h, src/MicroOcpp/Model/ConnectorBase/ConnectorsCommon.cpp, src/MicroOcpp/Model/Reservation/ReservationService.cpp, src/MicroOcpp/Model/Reset/ResetService.cpp, src/MicroOcpp/Operations/ReserveNow.cpp, src/MicroOcpp/Operations/StatusNotification.cpp, src/MicroOcpp/Operations/StatusNotification.h, src/MicroOcpp/Version.h, src/MicroOcpp_c.cpp, src/MicroOcpp_c.h, tests/ChargingSessions.cpp, tests/ConfigurationBehavior.cpp, tests/LocalAuthList.cpp, tests/Reservation.cpp, tests/Reset.cpp
Introduce a new function `getChargePointStatus()` in the C/C++ API which returns the OCPP field ChargePointStatus as reported via StatusNotification.
Furthermore, this PR changes the scoped enum ChargePointStatus in namespace MicroOcpp to a C-style enum not lying in a namespace. This could break your integration if you fetched the ChargePointStatus over the Connector class (and going beyond the API). To upgrade, the following changes are necessary:
- Definitions: `MicroOcpp::ChargePointStatus myStatus;` --> `ChargePointStatus myStatus;`
- Literals: `MicroOcpp::ChargePointStatus::Available` --> `ChargePointStatus_Available`
- Null-literal: `MicroOcpp::ChargePointStatus::NOT_SET` --> `ChargePointStatus_UNDEFINED`
This refactoring step is part of the changes to make C integrations easier. …
=> Expose ChargePointStatus in API

CHANGELOG.md, CMakeLists.txt, src/MicroOcpp.cpp, src/MicroOcpp.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.h, src/MicroOcpp/Model/ConnectorBase/UnlockConnectorResult.h, src/MicroOcpp/Operations/UnlockConnector.cpp, src/MicroOcpp/Operations/UnlockConnector.h, src/MicroOcpp_c.cpp, src/MicroOcpp_c.h, tests/Api.cpp, tests/ChargingSessions.cpp
Add the build flag `MO_ENABLE_CONNECTOR_LOCK` which allows to configure a connector lock.
Two OCPP features depend on a lock: the message UnlockConnector and the configuration UnlockConnectorOnEVSideDisconnect. The new build flag has the following effect:
- For chargers with a socket, set `MO_ENABLE_CONNECTOR_LOCK=1`: `setOnUnlockConnectorInOut(...)` remains as it is and UnlockConnectorOnEVSideDisconnect becomes read-write.
- For chargers with fixed cable, the default `MO_ENABLE_CONNECTOR_LOCK=0` applies: the function `setOnUnlockConnectorInOut(...)` in the API gets disabled and UnlockConnectorOnEVSideDisconnect remains read-only and is false.
=> Connector Lock build switch

.gitignore, CHANGELOG.md, CMakeLists.txt, src/MicroOcpp.cpp, src/MicroOcpp/Core/Context.cpp, src/MicroOcpp/Core/Context.h, src/MicroOcpp/Core/FilesystemAdapter.cpp, src/MicroOcpp/Core/FilesystemUtils.cpp, src/MicroOcpp/Core/Ftp.h, src/MicroOcpp/Core/FtpMbedTLS.cpp, src/MicroOcpp/Core/Time.h, src/MicroOcpp/Model/Diagnostics/DiagnosticsService.cpp, src/MicroOcpp/Model/Diagnostics/DiagnosticsService.h, src/MicroOcpp/Model/FirmwareManagement/FirmwareService.cpp, src/MicroOcpp/Model/FirmwareManagement/FirmwareService.h, tests/FirmwareManagement.cpp, tests/helpers/testHelper.cpp, tests/helpers/testHelper.h, tests/ocppEngineLifecycle.cpp
Provide a default FTP firmware updater.
The UpdateFirmware handler now triggers an FTP download which which can be set up to store all data on flash. This PR includes a full default OTA implementation for the ESP32 on Arduino (using the [Update](https://github.com/espressif/arduino-esp32/tree/3.0.1/libraries/Update) library) as a reference on how to store the FTP traffic on flash.
Furthermore, this PR contains unit tests for the FirmwareService and cleans up the existing OTA procedure a bit.
The OTA reference on the ESP32 replaces the previous HTTP-based reference.
=> Built-in firmware updates over FTP

CHANGELOG.md, CMakeLists.txt, src/MicroOcpp/Model/ConnectorBase/ChargePointErrorData.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.h, tests/ChargePointError.cpp
This adds the error severity field to the MO error reporting mechanism. The severity can be used to avoid that less important errors are being reported to the server while still being in a highly severe error condition. If the most severe error is resolved, then MO reports the next most severe error. This behavior is useful for some backend systems.
See this example for changing the severity:
```cpp
addErrorDataInput([] () -> ErrorData {
if (/* error condition */) {
ErrorData error = "OtherError";
error.severity = 2; //increase severity to `2` (default is `1`)
return error;
}
return nullptr;
});
```
The new build option `MO_REPORT_NOERROR=1` applies to errors which don't lead to the Faulted status, i.e. where `error.isFaulted == false` (for example, the charger reports the WeakSignal …
=> StatusNotification error severity mechanism & report resolved errors

CHANGELOG.md, src/MicroOcpp.cpp, src/MicroOcpp/Core/Request.cpp, src/MicroOcpp/Core/Request.h, src/MicroOcpp/Core/RequestQueue.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/ConnectorBase/ConnectorsCommon.cpp, src/MicroOcpp/Model/Metering/MeteringService.cpp, src/MicroOcpp/Model/Reset/ResetService.cpp, src/MicroOcpp/Model/Transactions/Transaction.cpp, src/MicroOcpp/Model/Transactions/Transaction.h, src/MicroOcpp/Model/Transactions/TransactionDeserialize.cpp, src/MicroOcpp/Operations/DataTransfer.cpp, src/MicroOcpp/Operations/DataTransfer.h, src/MicroOcpp/Operations/GetLocalListVersion.cpp, src/MicroOcpp/Operations/SendLocalList.cpp, src/MicroOcpp/Operations/StartTransaction.cpp, src/MicroOcpp/Operations/StatusNotification.h, src/MicroOcpp/Operations/UnlockConnector.cpp, src/MicroOcpp/Operations/UnlockConnector.h
This PR contains fixes for passing the OCTT test cases. A big shout out to @heakins who contributed back the patches to MicroOCPP!
For more information on the fixed issues, see the detailed commit messages.
The fixes addressing the rejection of SendLocalList, GetLocalListVersion and UnlockConnector have already been superseded on main. To disable Local Authorization Lists, set the build flag `MO_ENABLE_LOCAL_AUTH=0`. The connector lock support is already disabled by default.
=> Fix OCTT test cases

CHANGELOG.md, src/MicroOcpp/Core/Time.cpp, src/MicroOcpp/Core/Time.h
Adds a build switch `MO_ENABLE_TIMESTAMP_MILLISECONDS` to enable / disable the millisecond support of the Timestamp class.
To enable, set `MO_ENABLE_TIMESTAMP_MILLISECONDS=1` (disabled by default). To keep the old behavior, disable the switch explicitly in the build settings.
If disabled, the milliseconds fraction of incoming ISO 8601 timestamps will be ignored. Outgoing ISO 8601 strings will omit the milliseconds.
This change saves a few bytes per Timestamp, with the class size being slightly reduced from 24B to 20B. While this ~17% saving is not too significant, it nevertheless fits the design philosophy of microcontroller optimization.
=> Make ISO 8601 Timestamp milliseconds support optional

CHANGELOG.md, CMakeLists.txt, src/MicroOcpp/Core/RequestQueue.cpp, src/MicroOcpp/Core/RequestQueue.h, src/MicroOcpp/Model/Boot/BootService.cpp, src/MicroOcpp/Model/Boot/BootService.h, tests/Boot.cpp, tests/helpers/testHelper.h
If the BootNotification is not accepted immediately, some messages should be delayed until the charger gets the BootNotification status Accepted (see the OCPP specs). This worked fine before #345 which introduced a regression bug.
=> Fix message send behavior when BootNotification Pending

CHANGELOG.md, src/MicroOcpp/Model/Metering/MeteringConnector.cpp, src/MicroOcpp/Model/Metering/MeteringService.cpp, src/MicroOcpp/Operations/MeterValues.cpp, src/MicroOcpp/Operations/MeterValues.h
When a charger is running a transaction while it doesn't have the OCPP timestamp from the BootNotification response yet (possible in PreBoot mode), then any initiated MeterValues request had a 1970-01-01... timestamp. That timestamp is adjusted now after receiving the BootNotification so that the time is displayed correctly in the backend system.
=> Fix MeterValues PreBoot year 1970 timestamps

CHANGELOG.md, CMakeLists.txt, src/MicroOcpp.cpp, src/MicroOcpp/Core/Configuration.cpp, src/MicroOcpp/Core/Configuration.h, src/MicroOcpp/Core/ConfigurationContainer.h, src/MicroOcpp/Core/ConfigurationContainerFlash.cpp, src/MicroOcpp/Model/Boot/BootService.cpp, src/MicroOcpp/Model/Boot/BootService.h, tests/Boot.cpp
Automatically migrate the persistent storage of MO on the controller if it originates from a previous MO version.
The persistent storage is extended and optimized in some new releases of MO, making the storage layout backwards-incompatible. To allow existing deployments to be continuously updated, it's necessary to handle the storage changes. The built-in migration is guaranteed to work from v1.2.0 onward. There could be some storage artifacts from before v1.2.0 which are not fully handled.
Examples includes:
- The transaction store has been refactored in #345. The migration function clears existing tx store files (if a FW update happened, then it is very likely that the charger was online and all transactions have been fully uploaded, so no data loss)
- In v0.3, the name of the main …
=> Migrate persistent storage from previous MO versions

CHANGELOG.md, src/MicroOcpp/Core/Request.cpp, src/MicroOcpp/Core/Request.h, src/MicroOcpp/Core/RequestQueue.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.h, src/MicroOcpp/Model/Diagnostics/DiagnosticsService.cpp, src/MicroOcpp/Model/Metering/MeterValue.cpp, src/MicroOcpp/Model/Metering/MeterValue.h, src/MicroOcpp/Model/Metering/MeteringConnector.cpp, src/MicroOcpp/Model/Metering/MeteringConnector.h, src/MicroOcpp/Model/Metering/MeteringService.cpp, src/MicroOcpp/Operations/MeterValues.cpp, src/MicroOcpp/Operations/MeterValues.h, src/MicroOcpp/Operations/TriggerMessage.cpp, tests/Metering.cpp
After the changes of #345, the message order of tx-related MeterValues didn't work anymore. This PR is the corresponding fix.
=> Fix MeterValues tx-related message order

CHANGELOG.md, src/MicroOcpp/Operations/ChangeConfiguration.cpp
When ChangeConfiguation tried to update a boolean config with an integer value, then the integer was converted to bool following the C convention (i.e. `0` is `false` and all other numbers mean `true`). That behavior is misleading and removed in this PR.
=> Remove int to bool conversion in ChangeConfiguation

CHANGELOG.md, src/MicroOcpp/Model/ConnectorBase/ConnectorsCommon.cpp, src/MicroOcpp/Operations/RemoteStartTransaction.cpp, tests/ConfigurationBehavior.cpp
This PR implements the behavior for AuthorizeRemoteTxRequests. Before, the configuration was declared as read-only with value false and couldn't be changed to true.
=> Support for AuthorizeRemoteTxRequests

CHANGELOG.md, src/MicroOcpp/Operations/SetChargingProfile.cpp
=> Fix txId in TxProfile as optional parameter (addresses #346)

src/MicroOcpp/Core/Memory.cpp
Extend the memory profiler API to write the stats to a JSON document
=> Print heap stats to JSON document

.github/workflows/documentation.yml, CHANGELOG.md, docs/benchmarks.md, tests/benchmarks/scripts/measure_heap.py
Adds a GitHub Action which measures the heap occupation of various test cases of an external test driver. The test driver needs to trigger some state changes on MicroOcpp to check for the expected results. For this purpose, this setup incorporates the MicroOcppSimulator which runs the OCPP-side communication to the test driver while handling its HTTP requests.
The heap measurement results are published to the [Benchmarks](https://matth-x.github.io/MicroOcpp/benchmarks/) page of the Docs. This is a follow up PR of #369
=> Generate heap benchmarks automatically

.github/workflows/documentation.yml, CHANGELOG.md, src/MicroOcpp.cpp, src/MicroOcpp/Model/Authorization/IdToken.cpp, src/MicroOcpp/Model/ConnectorBase/Connector.h, src/MicroOcpp/Model/Metering/MeterValuesV201.cpp, src/MicroOcpp/Model/RemoteControl/RemoteControlService.cpp, src/MicroOcpp/Model/RemoteControl/RemoteControlService.h, src/MicroOcpp/Model/Reset/ResetService.cpp, src/MicroOcpp/Model/Transactions/Transaction.cpp, src/MicroOcpp/Model/Transactions/Transaction.h, src/MicroOcpp/Model/Transactions/TransactionService.cpp, src/MicroOcpp/Model/Transactions/TransactionService.h, src/MicroOcpp/Model/Transactions/TransactionStore.cpp, src/MicroOcpp/Model/Transactions/TransactionStore.h, src/MicroOcpp/Model/Variables/Variable.cpp, src/MicroOcpp/Model/Variables/Variable.h, src/MicroOcpp/Model/Variables/VariableContainer.cpp, src/MicroOcpp/Model/Variables/VariableContainer.h, src/MicroOcpp/Model/Variables/VariableService.cpp, src/MicroOcpp/Model/Variables/VariableService.h, src/MicroOcpp/Operations/RequestStartTransaction.cpp, src/MicroOcpp/Operations/RequestStartTransaction.h, src/MicroOcpp/Operations/TransactionEvent.cpp, src/MicroOcpp/Operations/TransactionEvent.h, tests/LocalAuthList.cpp, tests/Reset.cpp, tests/Transactions.cpp, tests/Variables.cpp, tests/benchmarks/scripts/measure_heap.py
This PR makes Variables and Transactions persistent over reboots. Furthermore, Transactions implement the TransactionMessageAttempts(-Interval) behavior now.
=> OCPP 2.0.1 persistent Variable and Transactions store

CHANGELOG.md, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, tests/ChargingSessions.cpp, tests/Transactions.cpp
Fix nullptr dereferencing error introduces in #345
=> Fix crash when initialized without FS access

.github/workflows/documentation.yml, .github/workflows/esp-idf.yml, CHANGELOG.md, README.md, library.json
Final cleanup for the v1.2.0 release
=> Prepare v1.2.0 release

CHANGELOG.md, src/MicroOcpp/Core/Configuration.cpp, src/MicroOcpp/Core/Configuration.h, src/MicroOcpp/Model/ConnectorBase/Connector.cpp, src/MicroOcpp/Model/Heartbeat/HeartbeatService.cpp, src/MicroOcpp/Model/Metering/MeteringConnector.cpp, src/MicroOcpp/Model/Metering/MeteringService.cpp, src/MicroOcpp/Model/Reset/ResetService.cpp
Fix a misleading debug OCPP message related to the Reset operation and reject negative integer values in ChangeConfiguration.
=> Minor OCPP 1.6 fixes

.github/workflows/documentation.yml, .github/workflows/tests.yml, CHANGELOG.md, SConscript.py, src/MicroOcpp/Core/ConfigurationKeyValue.cpp, src/MicroOcpp/Core/ConfigurationKeyValue.h, src/MicroOcpp/Core/Configuration_c.cpp, src/MicroOcpp/Core/Configuration_c.h, src/MicroOcpp/Model/Transactions/Transaction.cpp, src/MicroOcpp/Model/Transactions/Transaction.h, src/MicroOcpp/Operations/GetConfiguration.cpp, src/MicroOcpp/Platform.h, src/MicroOcpp_c.cpp, src/MicroOcpp_c.h, tests/Api.cpp, tests/ChargingSessions.cpp
Simplify some aspects of custom platform integrations:
* Extend C-API
* Revise Configurations C-API
* Add parentIdTag getter in Transactions C-API
* Move Console Cb and Rng Cb to Platform.h
* Simplify the usage of custom FilesystemAdapters
* Add `ocpp_addMeterValueInputIntTx` to support reading Tx start and stop values
* Revise SCons support
* Built-in support for write-only Configurations
=> Improvements for custom platform integrations
